"""added is_available column to listings

Revision ID: bd38311349f7
Revises: 7bc8e3b1f68c
Create Date: 2025-05-31 11:45:02.040167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd38311349f7'
down_revision: Union[str, None] = '7bc8e3b1f68c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'is_available')
    # ### end Alembic commands ###
